<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.hb.dokkan</groupId>
    <artifactId>dokkan-web</artifactId>
    <packaging>pom</packaging>
    <version>1.0.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>21</java.version>
        <spring.version>3.2.5</spring.version>
        <org.mapstruct.version>1.4.1.Final</org.mapstruct.version>
        <mybatis-plus.version>3.5.10.1</mybatis-plus.version>
        <fastjson.version>1.2.71</fastjson.version>
        <hikaricp.version>6.2.1</hikaricp.version>
        <google-guava.version>32.0.1-jre</google-guava.version>
        <hutool.version>5.8.24</hutool.version>
        <sa-tokan.version>1.41.0</sa-tokan.version>
        <freemarker.version>2.3.34</freemarker.version>
        <dokkan.version>1.0.0-SNAPSHOT</dokkan.version>
        <jsoup.version>1.17.2</jsoup.version>
        <opencc4j.version>1.6.2</opencc4j.version>
        <elasticsearch.version>7.17.28</elasticsearch.version>
        <easy-es.version>3.0.0</easy-es.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!--内部依赖 start-->
            <dependency>
                <groupId>com.hb.dokkan</groupId>
                <artifactId>dokkan-common</artifactId>
                <version>${dokkan.version}</version>
            </dependency>
            <dependency>
                <groupId>com.hb.dokkan</groupId>
                <artifactId>dokkan-infrastructure</artifactId>
                <version>${dokkan.version}</version>
            </dependency>
            <dependency>
                <groupId>com.hb.dokkan</groupId>
                <artifactId>dokkan-service</artifactId>
                <version>${dokkan.version}</version>
            </dependency>
            <dependency>
                <groupId>com.hb.dokkan</groupId>
                <artifactId>dokkan-api</artifactId>
                <version>${dokkan.version}</version>
            </dependency>
            <dependency>
                <groupId>com.hb.dokkan</groupId>
                <artifactId>dokkan-config</artifactId>
                <version>${dokkan.version}</version>
            </dependency>
            <!--内部依赖 end-->

            <!-- HikariCP连接池-->
            <dependency>
                <groupId>com.zaxxer</groupId>
                <artifactId>HikariCP</artifactId>
                <version>${hikaricp.version}</version>
            </dependency>

            <!--springboot管理-->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!--springboot管理-->

            <!--es相关-->
            <dependency>
                <groupId>co.elastic.clients</groupId>
                <artifactId>elasticsearch-java</artifactId>
                <exclusions>
                    <exclusion>
                        <groupId>co.elastic.clients</groupId>
                        <artifactId>elasticsearch-rest-client</artifactId>
                    </exclusion>
                </exclusions>
                <version>${elasticsearch.version}</version>
            </dependency>
            <dependency>
                <groupId>org.elasticsearch</groupId>
                <artifactId>elasticsearch</artifactId>
                <version>${elasticsearch.version}</version>
            </dependency>
            <dependency>
                <groupId>org.elasticsearch.client</groupId>
                <artifactId>elasticsearch-rest-client</artifactId>
                <version>${elasticsearch.version}</version>
            </dependency>
            <dependency>
                <groupId>org.elasticsearch</groupId>
                <artifactId>elasticsearch-geo</artifactId>
                <version>${elasticsearch.version}</version>
            </dependency>
            <dependency>
                <groupId>org.dromara.easy-es</groupId>
                <artifactId>easy-es-boot-starter</artifactId>
                <version>${easy-es.version}</version>
            </dependency>
            <!--es相关-->

            <!--fastjson start-->
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>fastjson</artifactId>
                <version>${fastjson.version}</version>
            </dependency>
            <!--fastjson end-->

            <!--mybatis start-->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-generator</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>

            <dependency>
                <groupId>org.freemarker</groupId>
                <artifactId>freemarker</artifactId>
                <version>${freemarker.version}</version>
            </dependency>
            <!--mybatis end-->

            <!--转换类 start-->
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${org.mapstruct.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${org.mapstruct.version}</version>
            </dependency>
            <!--转换类 end-->

            <!-- 通用工具类 start-->
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${google-guava.version}</version>
            </dependency>

            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>${hutool.version}</version>
            </dependency>

            <dependency>
                <groupId>org.jsoup</groupId>
                <artifactId>jsoup</artifactId>
                <version>${jsoup.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.houbb</groupId>
                <artifactId>opencc4j</artifactId>
                <version>${opencc4j.version}</version>
            </dependency>
            <!-- 通用工具类 end-->

            <!-- Sa-Token 权限认证，在线文档：https://sa-token.cc -->
            <dependency>
                <groupId>cn.dev33</groupId>
                <artifactId>sa-token-spring-boot3-starter</artifactId>
                <version>${sa-tokan.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <modules>
        <module>dokkan-common</module>
        <module>dokkan-api</module>
        <module>dokkan-config</module>
        <module>dokkan-starter</module>
        <module>dokkan-service</module>
        <module>dokkan-infrastructure</module>
    </modules>


</project>