spring.application.name=dokkan-web
server.port=${port}
server.servlet.context-path=/dokkan

#数据库
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${db_url}
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}

#hikari相关配置
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.pool-name=HikariCP
#最小空闲连接数
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=120000
#最大连接数
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.auto-commit=true



#mybatis
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

#线程池相关设置
thread.pool.corePoolSize=15
thread.pool.maxPoolSize=45
thread.pool.keepAliveSeconds=1200
thread.pool.queueCapacity=40

#restTemplate相关配置
http.pool.rest-template.max-total=1000
http.pool.rest-template.default-max-per-route=300
http.pool.rest-template.connection-request-timeout=60
http.pool.rest-template.read-timeout=60
http.pool.rest-template.connect-timeout=60

#webClient配置
http.pool.web-client.connect-timeout-mills=10000
http.pool.web-client.max-connections=1000
http.pool.web-client.read-timeout-seconds=30
http.pool.web-client.write-timeout-seconds=30
http.pool.web-client.max-idle-time-seconds=30
http.pool.web-client.max-life-time-seconds=60
http.pool.web-client.evict-in-background-time-seconds=120

#concurrency配置
http.pool.concurrency.batch-delay-mills=1000
http.pool.concurrency.batch-size=1000
http.pool.concurrency.semaphore-permits=100

# 设置 Jackson 的属性命名策略为下划线风格 (snake_case)
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.deserialization.fail-on-unknown-properties=true

#es相关
easy-es.address=${es_address}
easy-es.global-config.db-config.map-underscore-to-camel-case=true